set(_CATKIN_CURRENT_PACKAGE "amr_ui")
set(amr_ui_VERSION "1.0.0")
set(amr_ui_MAINTAINER "Alexander Hagg <alexander.hagg@inf.h-brs.de>")
set(amr_ui_PACKAGE_FORMAT "1")
set(amr_ui_BUILD_DEPENDS "rospy" "actionlib" "tf" "sensor_msgs" "std_msgs" "geometry_msgs" "amr_msgs" "amr_srvs" "python-pyside")
set(amr_ui_BUILD_EXPORT_DEPENDS "rospy" "actionlib" "tf" "sensor_msgs" "std_msgs" "geometry_msgs" "amr_msgs" "amr_srvs" "python-pyside")
set(amr_ui_BUILDTOOL_DEPENDS "catkin")
set(amr_ui_BUILDTOOL_EXPORT_DEPENDS )
set(amr_ui_EXEC_DEPENDS "rospy" "actionlib" "tf" "sensor_msgs" "std_msgs" "geometry_msgs" "amr_msgs" "amr_srvs" "python-pyside")
set(amr_ui_RUN_DEPENDS "rospy" "actionlib" "tf" "sensor_msgs" "std_msgs" "geometry_msgs" "amr_msgs" "amr_srvs" "python-pyside")
set(amr_ui_TEST_DEPENDS )
set(amr_ui_DOC_DEPENDS )
set(amr_ui_DEPRECATED "")