set(_CATKIN_CURRENT_PACKAGE "amr_perception")
set(amr_perception_VERSION "1.0.0")
set(amr_perception_MAINTAINER "Alexander Hagg <alexander.hagg@inf.h-brs.de>")
set(amr_perception_PACKAGE_FORMAT "1")
set(amr_perception_BUILD_DEPENDS "roscpp" "geometry_msgs" "dynamic_reconfigure" "amr_msgs" "amr_srvs" "sensor_msgs")
set(amr_perception_BUILD_EXPORT_DEPENDS "roscpp" "geometry_msgs" "dynamic_reconfigure" "amr_msgs" "amr_srvs" "sensor_msgs")
set(amr_perception_BUILDTOOL_DEPENDS "catkin")
set(amr_perception_BUILDTOOL_EXPORT_DEPENDS )
set(amr_perception_EXEC_DEPENDS "roscpp" "geometry_msgs" "dynamic_reconfigure" "amr_msgs" "amr_srvs" "sensor_msgs")
set(amr_perception_RUN_DEPENDS "roscpp" "geometry_msgs" "dynamic_reconfigure" "amr_msgs" "amr_srvs" "sensor_msgs")
set(amr_perception_TEST_DEPENDS )
set(amr_perception_DOC_DEPENDS )
set(amr_perception_DEPRECATED "")