set(_CATKIN_CURRENT_PACKAGE "amr")
set(amr_VERSION "1.0.0")
set(amr_MAINTAINER "Alexander Hagg <alexander.hagg@inf.h-brs.de>")
set(amr_PACKAGE_FORMAT "1")
set(amr_BUILD_DEPENDS )
set(amr_BUILD_EXPORT_DEPENDS "amr_braitenberg" "amr_stage_worlds" "amr_navigation" "amr_perception" "amr_mapping" "amr_exploration" "amr_srvs" "amr_stage" "amr_localization" "amr_ui" "amr_bugs" "amr_msgs" "amr_binaries" "amr_tools")
set(amr_BUILDTOOL_DEPENDS "catkin")
set(amr_BUILDTOOL_EXPORT_DEPENDS )
set(amr_EXEC_DEPENDS "amr_braitenberg" "amr_stage_worlds" "amr_navigation" "amr_perception" "amr_mapping" "amr_exploration" "amr_srvs" "amr_stage" "amr_localization" "amr_ui" "amr_bugs" "amr_msgs" "amr_binaries" "amr_tools")
set(amr_RUN_DEPENDS "amr_braitenberg" "amr_stage_worlds" "amr_navigation" "amr_perception" "amr_mapping" "amr_exploration" "amr_srvs" "amr_stage" "amr_localization" "amr_ui" "amr_bugs" "amr_msgs" "amr_binaries" "amr_tools")
set(amr_TEST_DEPENDS )
set(amr_DOC_DEPENDS )
set(amr_DEPRECATED "")