set(_CATKIN_CURRENT_PACKAGE "amr_msgs")
set(amr_msgs_VERSION "1.0.0")
set(amr_msgs_MAINTAINER "Alexander Hagg <alexander.hagg@inf.h-brs.de>")
set(amr_msgs_PACKAGE_FORMAT "1")
set(amr_msgs_BUILD_DEPENDS "actionlib" "actionlib_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs")
set(amr_msgs_BUILD_EXPORT_DEPENDS "actionlib" "actionlib_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs")
set(amr_msgs_BUILDTOOL_DEPENDS "catkin")
set(amr_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(amr_msgs_EXEC_DEPENDS "actionlib" "actionlib_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs")
set(amr_msgs_RUN_DEPENDS "actionlib" "actionlib_msgs" "sensor_msgs" "geometry_msgs" "nav_msgs")
set(amr_msgs_TEST_DEPENDS )
set(amr_msgs_DOC_DEPENDS )
set(amr_msgs_DEPRECATED "")