set(_CATKIN_CURRENT_PACKAGE "amr_braitenberg")
set(amr_braitenberg_VERSION "1.0.0")
set(amr_braitenberg_MAINTAINER "Alexander Hagg <alexander.hagg@inf.h-brs.de>")
set(amr_braitenberg_PACKAGE_FORMAT "1")
set(amr_braitenberg_BUILD_DEPENDS "roscpp" "dynamic_reconfigure" "amr_msgs" "amr_srvs" "amr_stage")
set(amr_braitenberg_BUILD_EXPORT_DEPENDS "roscpp" "dynamic_reconfigure" "amr_msgs" "amr_srvs" "amr_stage")
set(amr_braitenberg_BUILDTOOL_DEPENDS "catkin")
set(amr_braitenberg_BUILDTOOL_EXPORT_DEPENDS )
set(amr_braitenberg_EXEC_DEPENDS "roscpp" "dynamic_reconfigure" "amr_msgs" "amr_srvs" "amr_stage")
set(amr_braitenberg_RUN_DEPENDS "roscpp" "dynamic_reconfigure" "amr_msgs" "amr_srvs" "amr_stage")
set(amr_braitenberg_TEST_DEPENDS )
set(amr_braitenberg_DOC_DEPENDS )
set(amr_braitenberg_DEPRECATED "")