set(amr_braitenberg_SETUP_PY_VERSION "1.0.0")
set(amr_braitenberg_SETUP_PY_SCRIPTS "")
set(amr_braitenberg_SETUP_PY_PACKAGES "amr_braitenberg")
set(amr_braitenberg_SETUP_PY_PACKAGE_DIRS "src/amr_braitenberg")
set(amr_braitenberg_SETUP_PY_MODULES "")
set(amr_braitenberg_SETUP_PY_MODULE_DIRS "")