set(_CATKIN_CURRENT_PACKAGE "amr_stage")
set(amr_stage_VERSION "1.0.0")
set(amr_stage_MAINTAINER "Alexander Hagg <alexander.hagg@inf.h-brs.de>")
set(amr_stage_PACKAGE_FORMAT "1")
set(amr_stage_BUILD_DEPENDS "roscpp" "std_msgs" "nav_msgs" "tf" "geometry_msgs" "sensor_msgs" "robot_state_publisher" "dynamic_reconfigure" "amr_msgs" "amr_srvs" "orocos_kdl")
set(amr_stage_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "nav_msgs" "tf" "geometry_msgs" "sensor_msgs" "robot_state_publisher" "dynamic_reconfigure" "amr_msgs" "amr_srvs" "orocos_kdl")
set(amr_stage_BUILDTOOL_DEPENDS "catkin")
set(amr_stage_BUILDTOOL_EXPORT_DEPENDS )
set(amr_stage_EXEC_DEPENDS "roscpp" "std_msgs" "nav_msgs" "tf" "geometry_msgs" "sensor_msgs" "robot_state_publisher" "dynamic_reconfigure" "amr_msgs" "amr_srvs" "orocos_kdl")
set(amr_stage_RUN_DEPENDS "roscpp" "std_msgs" "nav_msgs" "tf" "geometry_msgs" "sensor_msgs" "robot_state_publisher" "dynamic_reconfigure" "amr_msgs" "amr_srvs" "orocos_kdl")
set(amr_stage_TEST_DEPENDS )
set(amr_stage_DOC_DEPENDS )
set(amr_stage_DEPRECATED "")