set(_CATKIN_CURRENT_PACKAGE "amr_stage_worlds")
set(amr_stage_worlds_VERSION "1.0.0")
set(amr_stage_worlds_MAINTAINER "Alexander Hagg <alexander.hagg@inf.h-brs.de>")
set(amr_stage_worlds_PACKAGE_FORMAT "1")
set(amr_stage_worlds_BUILD_DEPENDS )
set(amr_stage_worlds_BUILD_EXPORT_DEPENDS )
set(amr_stage_worlds_BUILDTOOL_DEPENDS "catkin")
set(amr_stage_worlds_BUILDTOOL_EXPORT_DEPENDS )
set(amr_stage_worlds_EXEC_DEPENDS )
set(amr_stage_worlds_RUN_DEPENDS )
set(amr_stage_worlds_TEST_DEPENDS )
set(amr_stage_worlds_DOC_DEPENDS )
set(amr_stage_worlds_DEPRECATED "")