set(_CATKIN_CURRENT_PACKAGE "amr_binaries")
set(amr_binaries_VERSION "1.0.0")
set(amr_binaries_MAINTAINER "Alexander Hagg <alexander.hagg@inf.h-brs.de>")
set(amr_binaries_PACKAGE_FORMAT "1")
set(amr_binaries_BUILD_DEPENDS )
set(amr_binaries_BUILD_EXPORT_DEPENDS )
set(amr_binaries_BUILDTOOL_DEPENDS "catkin")
set(amr_binaries_BUILDTOOL_EXPORT_DEPENDS )
set(amr_binaries_EXEC_DEPENDS )
set(amr_binaries_RUN_DEPENDS )
set(amr_binaries_TEST_DEPENDS )
set(amr_binaries_DOC_DEPENDS )
set(amr_binaries_DEPRECATED "")