set(_CATKIN_CURRENT_PACKAGE "amr_srvs")
set(amr_srvs_VERSION "1.0.0")
set(amr_srvs_MAINTAINER "Alexander Hagg <alexander.hagg@inf.h-brs.de>")
set(amr_srvs_PACKAGE_FORMAT "1")
set(amr_srvs_BUILD_DEPENDS "geometry_msgs" "amr_msgs")
set(amr_srvs_BUILD_EXPORT_DEPENDS "geometry_msgs" "amr_msgs")
set(amr_srvs_BUILDTOOL_DEPENDS "catkin")
set(amr_srvs_BUILDTOOL_EXPORT_DEPENDS )
set(amr_srvs_EXEC_DEPENDS "geometry_msgs" "amr_msgs")
set(amr_srvs_RUN_DEPENDS "geometry_msgs" "amr_msgs")
set(amr_srvs_TEST_DEPENDS )
set(amr_srvs_DOC_DEPENDS )
set(amr_srvs_DEPRECATED "")